quarkus.smallrye-openapi.info-title=Rest Api
#%dev.quarkus.smallrye-openapi.info-title=Example API (development)
#%test.quarkus.smallrye-openapi.info-title=Example API (test)
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=Just an example service
quarkus.smallrye-openapi.info-terms-of-service=Your terms here
quarkus.smallrye-openapi.info-contact-email=marcoberri@gmail.com
quarkus.smallrye-openapi.info-contact-name=API Support
quarkus.smallrye-openapi.info-contact-url=https://www.marcoberri.it
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html
# configure the MongoDB client for a replica set of two nodes
quarkus.mongodb.connection-string=mongodb://localhost:27017
# mandatory if you don't specify the name of the database using @MongoEntity
quarkus.mongodb.database=FastUrl
quarkus.mongodb.tracing.enabled=true

quarkus.application.ui-header={applicationName}
quarkus.arc.dev-mode.generate-dependency-graphs=TRUE
quarkus.banner.enabled=false
